---
layout: post
author: ainochi-kor
title: React/14. 에러 경계(Error Boundaries)
---

## 에러 경계의 소개

UI의 일부분에 존재하는 자바스크립트 에러가 전체 애플리케이션을 중단시켜서는 안된다. React 사용자들이 겪는 이 문제를 해결하기 위해 React 16에서는 에러 경계("error boundary")라는 새로운 개념이 도입되었다.  
  
에러 경계는 **하위 컴포넌트 트리의 어디에서든 자바스크립트 에러를 기록하며 깨진 컴포넌트 트리 대신 폴백 UI를 보여주는 React 컴포넌트**이다. 에러 경계는 렌더링 도중 생명주기 메서드 및 그 아래에 있는 전체 트리에서 에러를 잡아낸다.

> #### Note
> 에러 경계는 다음과 같은 에러는 포착하지 않는다.
> - 이벤트 핸들러
> - 비동기적 코드 (setTimeout / requestAnimationFrame 콜백)
> - 서버 사이드 렌더링
> - 자식에서가 아닌 에러 경계 자체에서 발생하는 에러

생명주기 메서드인 static getDerivedStateFromError() 와 componentDidCatch() 중 하나 (혹은 둘 다)를 정의하면 클래스 컴포넌트 자체가 에러 경계가 된다. 에러가 발생한 뒤에 폴백 UI를 렌더링하려면 static getDerivedStateFromError()를 사용하고, 에러 정보를 기록하려면 componentDidCatch()를 사용하면 된다.

``` js
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false}
  }

  static getDerivedStateFromError(error) {
    // 다음 렌더링에서 폴백 UI가 보이도록 상태를 업데이트 한다.
    return { hasError: true };
  }

  conponentDisCatch(error, errorInfo) {
    // 에러 리포팅 서비스에 에러를 기록할 수 있다.
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if(this. state.hasError) {
      // 폴백 UI를 커스텀하여 렌더링할 수 있다.
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}
```

그런 다음엔 아래와 같이 일반 컴포넌트로 사용할 수 있다.

``` js
<ErrorBoundary>
  <MyWidget />
</ErrorBoundary>
```

에러 경계는 자바스크립트 catch {} 구문과 유사하게 동작하지만 컴포넌트에 적용된다. 오직 클래스 컴포넌트만이 에러 경계가 될 수 있다.  
  
**에러 경계는 트리 내에서 하위에 존재하는 컴포넌트의 에러만을 포착한다.** 에러 경계 자체적으로는 에러를 포착할 수 없다. 에러 경계가 에러 메시지를 렌더링하는데 실패한다면 에러는 그 위의 가장 가까운 에러 경계로 전파될 것이다. 이 또한 자바스크립트의 catch {} 구분이 동작하는 방식과 유사하다.

---

라이브 데모

[React 16으로 구현된 에러 경계 선언과 사용 예시]

``` html
<div id="root">
</div>
```

``` js
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null, errorInfo: null };
  }
  
  componentDidCatch(error, errorInfo) {
    // Catch errors in any components below and re-render with error message
    this.setState({
      error: error,
      errorInfo: errorInfo
    })
    // You can also log error messages to an error reporting service here
  }
  
  render() {
    if (this.state.errorInfo) {
      // Error path
      return (
        <div>
          <h2>Something went wrong.</h2>
          <details style={{ whiteSpace: 'pre-wrap' }}>
            {this.state.error && this.state.error.toString()}
            <br />
            {this.state.errorInfo.componentStack}
          </details>
        </div>
      );
    }
    // Normally, just render children
    return this.props.children;
  }  
}

class BuggyCounter extends React.Component {
  constructor(props) {
    super(props);
    this.state = { counter: 0 };
    this.handleClick = this.handleClick.bind(this);
  }
  
  handleClick() {
    this.setState(({counter}) => ({
      counter: counter + 1
    }));
  }
  
  render() {
    if (this.state.counter === 5) {
      // Simulate a JS error
      throw new Error('I crashed!');
    }
    return <h1 onClick={this.handleClick}>{this.state.counter}</h1>;
  }
}

function App() {
  return (
    <div>
      <p>
        <b>
          This is an example of error boundaries in React 16.
          <br /><br />
          Click on the numbers to increase the counters.
          <br />
          The counter is programmed to throw when it reaches 5. This simulates a JavaScript error in a component.
        </b>
      </p>
      <hr />
      <ErrorBoundary>
        <p>These two counters are inside the same error boundary. If one crashes, the error boundary will replace both of them.</p>
        <BuggyCounter />
        <BuggyCounter />
      </ErrorBoundary>
      <hr />
      <p>These two counters are each inside of their own error boundary. So if one crashes, the other is not affected.</p>
      <ErrorBoundary><BuggyCounter /></ErrorBoundary>
      <ErrorBoundary><BuggyCounter /></ErrorBoundary>
    </div>
  );
}



ReactDOM.render(
  <App />,
  document.getElementById('root')
);

```
